version: "3.1"
services:
    mongodb:
        image: mongo
        container_name: mongodb
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mongo
            - MONGO_INITDB_ROOT_PASSWORD=sw55amp
            - MONGO_DB_USERNAME=alanda
            - MONGO_DB_PASSWORD=sw55amp
        ports:
            - 27017:27017
        restart: unless-stopped
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongodb
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_MONGODB_ADMINUSERNAME=mongo
            - ME_CONFIG_MONGODB_ADMINPASSWORD=sw55amp
            - ME_CONFIG_BASICAUTH_USERNAME=admin
            - ME_CONFIG_BASICAUTH_PASSWORD=admin123
        depends_on:
            - mongodb
        ports:
            - 8081:8081
        restart: unless-stopped
    object-store-db:
        restart: always
        build: ./
        image: mongodb-service
        links:
            - mongodb
        depends_on:
            -   mongodb
        ports:
            - 8080:8080
        environment:
            - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin
            - SPRING_DATA_MONGODB_HOST=mongodb
            - SPRING_DATA_MONGODB_PORT=27017
            - SPRING_DATA_MONGODB_USERNAME=mongo
            - SPRING_DATA_MONGODB_PASSWORD=sw55amp
            - SPRING_DATA_MONGODB_AUTO_INDEX_CREATION=true