openapi: '3.0.3'
info:
  version: 1.0.0
  title: Object Store Database Endpoints
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: christophhagelkruys@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: http://localhost:8080/types/v1
    description: Local server

paths:
  '/types':
    get:
      summary: Get all types
      operationId: getTypes
      responses:
        '200':
          $ref: '#/components/responses/TypesResponse'
        '401':
          description: Unauthorized
        '500':
          description: InternalServerError
    post:
      summary: Create Type
      operationId: createType
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Type'
      responses:
        '200':
          $ref: '#/components/responses/TypeResponse'
        '401':
          description: Unauthorized
        '500':
          description: InternalServerError

  '/types/{id}':
    get:
      summary: Get Type by id
      operationId: getTypeById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/TypeResponse'
        '401':
          description: Unauthorized
        '404':
          description: Type Not Found
        '500':
          description: InternalServerError
    put:
      summary: Update type by Id
      operationId: updateTypeById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Type'
      responses:
        '200':
          $ref: '#/components/responses/TypeResponse'
        '401':
          description: Unauthorized
        '404':
          description: Type Not Found
        '500':
          description: InternalServerError
  '/types/{typeId}/collections':
    post:
      summary: Create Collection for specified Type
      operationId: createCollectionForType
      parameters:
        - in: path
          name: typeId
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Accepted
        '401':
          description: Unauthorized
        '404':
          description: Type Not Found
        '409':
          description: Already Exists
        '500':
          description: InternalServerError


components:
  schemas:

    Type:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        keyDefinitions:
          type: array
          items:
            $ref: '#/components/schemas/KeyDefinition'
    KeyDefinition:
      type: object
      properties:
        key:
          type: string
        type:
          type: string

  responses:
    TypesResponse:
      description: An array of types
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Type'
    TypeResponse:
      description: Requested Type
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Type'

externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
